### ISSUE TITLE
Make `pyright` in CI mostly consistent with the latest Pylance

### ISSUE THREAD

**Issue by blakeNaccarato** [blakeNaccarato/boilerdata#58]
This [CI log](https://github.com/blakeNaccarato/boilerdata/runs/6760965054?check_suite_focus=true) shows that Pyright on CI reports "unnecessary type ignore" and "cannot access member" in places where the local Pylance/Pyright does not report it.

**Comment by blakeNaccarato** [comment]
Issue microsoft/pylance-release#2989 may have been interfering here as well.

**Comment by blakeNaccarato** [comment]
The advice in microsoft/pylance-release#3045 will help. I need to explicitly specify stubs in `typings` both locally and in CI, and I will use [jakebailey/pyright-action](https://github.com/jakebailey/pyright-action) to simplify CI.

**Comment by blakeNaccarato** [comment]
Behavior is out-of-sync again

**Comment by blakeNaccarato** [comment]
I've started maintaining my own version of the stubs that come bundled with Pylance that I can add as a submodule to repos that need `pyright` to work like Pylance in CI/CD. That repo is over at https://github.com/blakeNaccarato/pylance-stubs-unofficial

**Comment by PierreSnell** [comment]
Hi @blakeNaccarato, 

Seems you managed to solve the problem with your own typeStubs. 
Could we keep the issue open ? I still have a difference in behaviour with pyright cli and pylance... 

System : 
```
pyright: 1.1.279
typeShed: python/typeshed.git (latest master)
typeStubs: :microsoft/python-type-stubs.git (latest master)
```

My only option to run it in CI for now is to just not run it... 

Thanks 
Have a great day

**Comment by blakeNaccarato** [comment]
Yeah @PierreSnell, I've arrived at a sort of flaky solution of manually updating https://github.com/blakeNaccarato/pylance-stubs-unofficial weekly with the contents of `~\.vscode\extensions\ms-python.vscode-pylance-<RELEASE>\dist\bundled\stubs`, then adding that to the `typings` directory in repos where I need it with `git submodule add ...`.

You also need to make sure the `submodules` option is configured in `actions/checkout` so your CI gets the stubs.

This effort reduces dozens of discrepancies to just one or two in a data science stack codebase of ~10k lines.

There is still the occasional line that fails checking locally or on CI but not the other way around. Also since I use the `reportUnneccessaryTypeIgnore` check, sometimes a local (necessary!) ignore gets flagged as unnecessary in CI. My solution to that is to disable the `reportUnneccessaryTypeIgnore` check in the entire file where those weird discrepancies pop up (since you can't disable the check line-by-line.

I suspect that the remaining discrepancies lie in the particular details of stub resolution order by Pylance, regarding the other stubs in `~\.vscode\extensions\ms-python.vscode-pylance-<RELEASE>\dist\`. See I only keep the `bundled/stubs` bit updated, because it's not clear how the other stub folders in `dist` are merged/layered.

Pyright only has one "layer" of stub finding by default, so Pylance must be doing some magic behind the scenes to compose all the stubs.

I am sticking with what I've got for now. I would like to eventually put this issue to bed for good, but we'll need the precise details of Pylance stub resolution (or perhaps that component of Pylance can be open-sourced?) to proceed.

I know I could just use mypy, but I don't want to maintain a mypy config AND a pyright config simultaneously, and I would like for pyright to "just work" in this application, eventually.

**Comment by PierreSnell** [comment]
Thanks a lot for this detailed explanation and tips ! 

I tried with the `.../vscode/.../dist/bundled/stubs` and pyright indeed working fine (as the vscode one) ! 😄 

I agree that it's a pain that cli and extension are not giving the same results and we should have an official repo like what you did (with all the pylance stubs). 

For mypy, the problem for me it's that it's static and is not as powerfull as dynamic checking like pylance. 
Also having to maintain the two is a pain.
